# Config file for automatic testing at travis-ci.org

language: python

# Faster, containerized builds
sudo: false

python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"

env:
  - SHELLS="ipython==4.2.0"
  - SHELLS="ptpython==0.34"

install:
  - pip install -U .
  - pip install pytest scripttest flake8
  - pip install -U "$SHELLS"

before_script:
  - flake8 .

# command to run tests, e.g. python setup.py test
script: python setup.py test

