# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
  - "pypy"

install:
    - "pip install -U ."
    - "pip install pytest scripttest"
# command to run tests, e.g. python setup.py test
script: py.test
